workshopapps/tropicalweather.web

backend/app/tests/test_weather_forecasts_immediate.py
backend/app/utils.py

Change how the endpoint parse the json from the openweathermap api

fix: refactor immediate forecasts endpoint

---

backend/app/models.py
backend/app/routers/weather.py
backend/app/tests/test_api.py
backend/app/tests/test_utils.py
backend/app/utils.py

- Created the weather forecast endpoint
- Added tests for the endpoint and utils used for it

feat(BAC-47): created the current weather endpoint

---

backend/Dockerfile

Dockerfile edit

---

backend/app/tests/conftest.py

Removed unused fixture from conftest

fix: (BAC-48)

---

frontend/src/App.jsx
frontend/src/pages/Promotions.jsx

Make `page/Home` default landing page

Fe Make Home Default Landing Page

---

backend/app/env.example
backend/app/main.py
backend/requirements.txt

* Add dependencies for caching
* Add redis database url to env.example
* fix the /status endpoint
Resolves: #114

fix: Add changes to the /status endpoint

---

backend/app/env.example
backend/app/main.py
backend/requirements.txt

Reverts workshopapps/weathery.web#145

Revert "fix: Add changes to the /status endpoint"

---

frontend/src/components/Home/PopularLocation.jsx
frontend/src/pages/Dashboard.jsx
frontend/src/styles/Home.css

[FRO-48 linear ticket](https://linear.app/team-gear/issue/FRO-48/add-or-save-location-user-story)
[FRO-49 linear ticket](https://linear.app/team-gear/issue/FRO-49/remove-location-user-story)
[Screencast from 11-30-2022 06:45:36 PM.webm](https://user-images.githubusercontent.com/49823605/204884853-a242dc4a-ac58-4da2-985c-cd95b92d9b20.webm)

FRO-48: Add location & FRO-49: Remove location

---

frontend/src/pages/Dashboard.jsx

[linear issue](https://linear.app/team-gear/issue/FRO-66/designers-review-of-our-webpage)

FRO-66/designers-review-of-our-webpage

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.jsx
frontend/src/pages/Settings.jsx
frontend/src/styles/Settings.css

**FRO-53**
- I created a settings page and made it responsive on mobile screens

FRO- 53 Access application settings

---

frontend/src/App.jsx
frontend/src/components/Footer.jsx
frontend/src/components/Header.jsx
frontend/src/components/MobileHeaderToggle.jsx
frontend/src/styles/ContactUs.css

link  to linear ticket:
[https://linear.app/team-gear/issue/FRO-81/implement-the-contact-us-page](https://linear.app/team-gear/issue/FRO-81/implement-the-contact-us-pagel)
screenshot:

FRO 81 - fixed issue of contact page not displaying

---

backend/app/main.py
backend/app/routers/share.py
backend/app/schemas.py
backend/app/utils/general.py
backend/tests/test_api.py
backend/tests/test_utils.py

- Generate share link to use in mobile app
- Tested the utils and endpoints
- Wrote a function to convert the uid back to city, state and country to be used by others. It will be used in the endpoint for getting weather condition for a shared location.

feat(BAC-102): Endpoint to generate file link

---

frontend/src/components/Footer.jsx
frontend/src/components/Home/HoulyUpdate.jsx
frontend/src/components/Home/Risk.jsx
frontend/src/pages/Home.jsx

This PR contains the fix made on the footer, (functionality: scroll to top onload, app and playstore button leads you to the appetizer page.).
[Link](https://linear.app/team-gear/issue/FRO-54/fix-the-about-us-page) to issue

FRO-54: Fix the About Us page

---

frontend/src/components/Home/Faqs.jsx
frontend/src/components/MobileHeaderToggle.jsx
frontend/src/pages/Home.jsx

Removed the features of the navbar and also other things
Link to [Linear](https://linear.app/team-gear/issue/FRO-67/remove-features-from-the-dashboard)

FRO-67 Remove features 

---

frontend/src/App.jsx
frontend/src/components/Dashboard/OptionsPopup.jsx
frontend/src/pages/Home.jsx
frontend/src/styles/Home.css

Add Api functionality to home/landing page

Fro lngpg fix

---

backend/app/routers/weather.py
backend/app/schemas.py
backend/app/tests/test_user_current_weather.py
backend/app/utils/user_current_forecast.py

Get User Current Weather Forecast, Including Weather Risk
This is an endpoint to get the current forecast of a location.
The location will be passed as lat and long. The response will be
* The current weather forecast
* The duration of the weather condition
* The state and city of the location
* The Intensity of the weather condition (Low, Moderate, High, Extreme)
* The risk for that time
* Response:
```json
{
"main": "Shower rain",
"datetime": "2020-01-01 12:00:00",
"end_datetime": "2020-01-01 12:00:00",
"risk": "Extreame Heat",
"state": "Lagos",
"city": "Ikorodu",
"country": "Nigeria",
}
```
linear: https://linear.app/team-gear/issue/BAC-66/get-user-current-weather-forecast-including-weather-risk

feat(BAC-66): Add weather current endpoint

---

backend/app/routers/weather.py
backend/app/schemas.py
backend/app/tests/test_user_current_weather.py
backend/app/utils/user_current_forecast.py

Get the Current Weather Forecast for an Address
This is an endpoint to get the current forecast of a location.
The location will be passed as an address, which will be geocoded
to get the lat and long. The response will be
* The current weather forecast
* The duration of the weather condition
* The state and city of the location
* The Intensity of the weather condition (Low, Moderate, High, Extreme)
* The risk for that time
Response:
```json
{
"main": "Shower rain",
"datetime": "2020-01-01 12:00:00",
"end_datetime": "2020-01-01 12:00:00",
"risk": "Extreame Heat",
"state": "Lagos",
"city": "Ikorodu",
"country": "Nigeria",
}
```
Linear: https://linear.app/team-gear/issue/BAC-67/get-the-current-weather-forecast-for-an-address

feat(BAC-67): Add currrent weather by address endpoint

---

backend/app/routers/weather.py
backend/app/schemas.py

Change function for getting city, state and country

fix: Add change to weather current endpoint

---

backend/app/celery_tasks/tasks.py
backend/app/conf/runtime.py
backend/app/conf/settings.py
backend/app/main.py
backend/app/tests/conftest.py
backend/app/tests/test_cache.py
backend/app/tests/test_logger.py
backend/app/utils/cache.py
backend/app/utils/fcm_service.py
backend/app/utils/logger.py
backend/app/utils/push_notification.py

- Fixed the FCM configuration, now fcm is working properly.
- Refactored the code to make it more organized.
- Wrote tests for newly created functions.

fix: fcm configuration

---

frontend/public/language/i18n/contact/ar.json
frontend/public/language/i18n/contact/en.json
frontend/public/language/i18n/dashboard/es.json
frontend/public/language/i18n/dashboard/fr.json
frontend/src/pages/ContactUs.jsx
frontend/src/pages/Home.jsx
frontend/src/pages/Settings.jsx

**FRO-96**
**https://linear.app/team-gear/issue/FRO-96/make-the-send-button-on-the-contact-us-page-functional*
The FAQ link goes to the right position now
The contact form when filled and submitted, shows a success message.

FRO-96 Fe fix contact form and faq routing

---

frontend/src/components/share/Share_popup.jsx
frontend/src/pages/Error404.jsx
frontend/src/styles/Error404.css

This PR contains the fix made on the ERROR404 PAGE
[Link](https://linear.app/team-gear/issue/FRO-55/implement-design-for-404-page) to issue

FRO-55: Implement design for 404 page

---

backend/app/main.py
backend/requirements.txt

added apm for performance monitoring for backend and sentry sdk to requirements file.

Added apm for backend

---

frontend/src/pages/Notificationsettings.jsx

I made the radio buttons and toggle button not to reset on page reload

fix: Fixed the inputs resetting issue

---

backend/app/templates/status.html
backend/app/utils/general.py

Update the status page to show the status of the current endpoints

Refactor: Add changes to status endpoint

---

frontend/src/libs/Home.js
frontend/src/pages/Home.jsx

FRO: change home timeline to 12 hour format

---

frontend/package.json
frontend/src/App.jsx

Reverts workshopapps/tropicalweather.web#255

Revert "Adjust routes to accunt for apm"

---

frontend/src/components/Footer.jsx
frontend/src/pages/Home.jsx

[linear ticket](https://linear.app/team-gear/issue/FRO-107/allow-location-access-after-blocking)

FRO-107: allow-location-access-after-blocking

---

frontend/src/pages/Home.jsx

fix: explain to user why location permission is

---

frontend/src/components/Dashboard/Share.jsx
frontend/src/pages/Dashboard.jsx
frontend/src/styles/Share.css

This PR contains the fix made on the share modal.
[Link](https://linear.app/team-gear/issue/FRO-124/improve-share-modal) to issue

FRO-124 : Improve Share modal.

---

frontend/src/components/Dashboard/Footer.jsx
frontend/src/pages/Dashboard.jsx

- Make changes to the dashboard footer to show language selection options
- Make the mobile version better with font sizing and spacing

Dashboard update
